export const ADD_INGRIDIENT_CONSTRUCTOR = "GET_INGRIDIENT_CONSTRUCTOR";
export const REMOVE_INGRIDIENT_CONSTRUCTOR = "REMOVE_INGRIDIENT_CONSTRUCTOR";
export const ADD_BUN_CONSTRUCTOR = "ADD_BUN_CONSTRUCTOR";
export const MOVE_INGRIDIENT_CONSTRUCTOR = "MOVE_INGRIDIENT_CONSTRUCTOR";
export const RESET_CONSTRUCTOR = "RESET_CONSTRUCTOR";